---
title: "Wellennachweis - umlaufende Rundnut"
author: "Quentin Huss, Nadine Schulz"
date: "14.06.2023"
output: pdf_document
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}

```




# 0 gegebene Größen  
## Geometrie  
```{r, echo=FALSE, results='asis'}
Tabelle_gegebene_Größen <- data.frame(
  "Wellendurchmesser" = c(dw),
  "Kerbgrunddurchmesser" = c(d),
  "Radius" = c(r),
  "Breite\ der\ Nut" = c(b)
)

library(kableExtra)

kbl(t(Tabelle_gegebene_Größen), booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped", "hold_position")) %>%
  add_header_above(c("in mm" = 2))

```
 
## Beanspruchung  

# 1 Bauteilwechselfestigkeiten  
## Kerbwirkungszahlen  

$$\beta_{\sigma_b} = `r round(beta_sigma, 3)`$$ 
  
$$\beta_{\tau} = `r round(beta_tau, 3)`$$  

## Gesamteinflussfaktoren    


$$K_{\sigma ,b} = `r round(K_ges_sigma, 3)`$$    
  
$$K_{\tau} = `r round(K_ges_tau, 3)`$$  



## Bauteilwechselfestigkeit  

$$\sigma_{bWK} = `r round(sigma_bWK, 3)` \dfrac{N}{mm^{2}}$$  
  
$$\tau_{tWK} = `r round(tau_bWK, 3)` \dfrac{N}{mm^{2}}$$  
  
# 2 Bauteilfließgrenzen  
  
$$\sigma_{bFK} = `r round(sigma_bFK, 3)` \dfrac{N}{mm^{2}}$$  
  
$$\tau_{tFK} = `r round(tau_tFK, 3)` \dfrac{N}{mm^{2}}$$  

# 3 Gestaltfestigkeit  

$$\sigma_{bADK} = `r round(sigma_bADK, 3)` \dfrac{n}{mm^{2}}$$    
  
$$\tau_{tADK} = `r round(tau_tADK, 3)` \dfrac{N}{mm^{2}}$$  

# 4 Sicherheiten  
$$S_F = `r round(S_F, 3)`$$    
  
$$S_D = `r round(S_D, 3)`$$ 
