---
title: "Wellennachweis - Keilwelle"
author: "Quentin Huss, Nadine Schulz"
date: "14.06.2023"
output: pdf_document
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
dw = 50
Name = "Absatz"
werkstoff = "42CrMo4"
z_Wert = 40
Welle = "Test"
beta_sigma = 2
beta_tau = 3
K_ges_sigma = 30
K_ges_tau = 29
sigma_bWK = 2038
tau_bWK = 239848
sigma_bFK = 48
tau_tFK = 439875
sigma_bADK = 34
tau_tADK = 457
S_F = 2
S_D = 4
```




# 0 gegebene Größen  
## Geometrie  
```{r, echo=FALSE, results='asis'}
Tabelle_gegebene_Größen <- data.frame(
    "Wellendurchmesser" = c(dw)
)

library(kableExtra)

knitr::kable(t(Tabelle_gegebene_Größen), booktabs = TRUE) %>%


```
 
## Beanspruchung  

# 1 Bauteilwechselfestigkeiten  
## Kerbwirkungszahlen  
\begin{center}
$$\beta_{\sigma_b} = `r beta_sigma`$$ 
   
$$\beta_{\tau} = `r beta_tau`$$  
  

## Gesamteinflussfaktoren  

$$K_{\sigma ,b} = `r K_ges_sigma`$$  
  
$$K_{\tau} = `r K_ges_tau`$$


## Bauteilwechselfestigkeit  

$$\sigma_{bWK} = `r sigma_bWK`\ \dfrac{N}{mm^{2}}$$
  
$$\tau_{tWK} = `r tau_bWK`\ \dfrac{N}{mm^{2}}$$



# 2 Bauteilfließgrenzen  
$$\sigma_{bFK} = `r sigma_bFK`\ \dfrac{N}{mm^{2}}$$  
  
$$\tau_{tFK} = `r tau_tFK`\ \dfrac{N}{mm^{2}}$$  

# 3 Gestaltfestigkeit  
$$\sigma_{bADK} = `r sigma_bADK`\ \dfrac{N}{mm^{2}}$$  
  
$$\tau_{tADK} = `r tau_tADK`\ \dfrac{N}{mm^{2}}$$  

# 4 Sicherheiten  
$$S_F = `r S_F`$$  
  
$$S_D = `r S_D`$$